### ISSUE TITLE
Which dataset is this model trained on?

### ISSUE THREAD

**Issue by holger-motional** [TropComplique/mtcnn-pytorch#12]
Hi, from the paper I infer that this method was trained for different datasets. Could you tell me which dataset your model was trained on?

**Comment by BrightXiaoHan** [comment]
The model is convert from caffe model trained by author of original paper. 
You can find dataset from the following links.
http://mmlab.ie.cuhk.edu.hk/projects/WIDERFace/
http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html
